version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
        command: |
          sudo pip install pipenv
          pipenv install
      - run: pytest -v